"""Photometer

These functions handle data files from spectrophotometers for easy and direct import

The functions are:

    * uprtek_import_spectrum - Imports the spectrum from a UPRtek spectrophotometer
    * uprtek_import_r_vals - Imports the R values generated by a UPRtek spectrophotometer
    * uprtek_file_import - Imports the UPRtek file and extracts the selected data
"""

import csv
import itertools


"""Imports a UPRtek data file and outputs a dictionary with the intensities for each wavelength

Note: UPRtek names these files as .xls, but they are actually formatted as tab-delimited text files
Note2: This has only been tested with the UPRtek CV600 and MK350N. Others may have a different file format

Parameters
----------
filename : String
    The filename to import
    
Returns
-------
dict
    A dictionary with the wavelengths and intensities, e.g.:
                                    {380: 0.048, 381: 0.051, ...}
"""
def uprtek_import_spectrum(filename: str):
    return uprtek_file_import(filename, 'spd')


"""Imports a UPRtek data file and outputs a dictionary with the R-Values

Note: UPRtek names these files as .xls, but they are actually formatted as tab-delimited text files
Note2: This has only been tested with the UPRtek CV600 and MK350N. Others may have a different file format

Parameters
----------
filename : String
    The filename to import
    
Returns
-------
dict
    A dictionary with the R-Values, e.g.:
                                    {'R1': 98.887482, 'R2': 99.234245, ...}
"""
def uprtek_import_r_vals(filename: str):
    return uprtek_file_import(filename, 'r_vals')


"""Imports a UPRtek data file and outputs a dictionary with the selected data

Note: UPRtek names these files as .xls, but they are actually formatted as tab-delimited text files
Note2: This has only been tested with the UPRtek CV600 and MK350N. Others may have a different file format

Parameters
----------
filename : String
    The filename to import
returntype: dict
    The type of data to return. Currently, either 'spd' or 'r_vals'
    
Returns
-------
dict
    A dictionary with the selected data
"""
def uprtek_file_import(filename: str, returntype: dict):
    with open(filename, mode='r', encoding='us-ascii') as csvFile:
        reader = csv.reader(csvFile, delimiter='\t')

        # Get UPRtek model from the first line, then set rows for reading data
        model = next(reader)[1]
        if model == 'CV600':
            spd_start = 40
            r_start = 18
            r_end = 33
        elif model == 'MK350NPLUS':
            spd_start = 46
            r_start = 26
            r_end = 41
        else:
            print('UPRtek model not available. Using the MK350N format, which could result in errors!')
            spd_start = 46
            r_start = 26
            r_end = 41

        # Extract the data and return
        if returntype == 'spd':
            spd = {}
            
            for row in itertools.islice(reader, spd_start, None):
                spd[int(row[0][0:3])] = float(row[1])

            return spd
        elif returntype == 'r_vals':
            r_vals = {}

            for row in itertools.islice(reader, r_start, r_end):
                r_vals[row[0]] = float(row[1])

            return r_vals
